# Generated by Django 5.1.6 on 2025-04-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
