# Generated by Django 5.1.8 on 2025-04-04 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_passagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_number', models.IntegerField(unique=True)),
                ('district', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'parking_spot',
            },
        ),
        migrations.AlterModelTable(
            name='passagelog',
            table='passage_log',
        ),
        migrations.CreateModel(
            name='ParkingSpotReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('parking_spot', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.parkingspot')),
                ('reserved_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parking_spot_reservation',
            },
        ),
    ]
