# Generated by Django 5.1.8 on 2025-04-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_parkingspot_alter_passagelog_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspotreservation',
            name='status',
            field=models.CharField(default='active', max_length=20),
            preserve_default=False,
        ),
    ]
